### ISSUE TITLE
Add plugins to boilerplate

### ISSUE THREAD

**Issue by vidurb** [miranj/craft#4]
Here are some suggestions:
- Craft Minify
- Craft Imager
- Expanded Singles
- Redactor
- Craft Inventory
- Environment Label
- Craft Typogrify
- Craft Relabel

Alternatively, I can add the default configurations for plugins that I have on hand and leave the plugins out of the package, if that's what you think is best.

As mentioned in one of the project notes, (IMHO) the best solution is to integrate a list of our most used plugins into the post install script so that they can be selected interactively and their default configurations can be added if necessary .

**Comment by rungta** [comment]
As discussed, we’ll add some of these plugins as part of our scaffolding (Imager + `_image`, Minify + CacheFlag + `_init` etc.) commits.

Everything else on this list (Relabel, Typogrify, Environment Label etc.) can be added to all projects by default. Not sure we need to have an interactive selection process in the install script at this stage.

We can add the selective process in the future if we find ourselves needing to uninstall some of these plugins on projects.

**Comment by vidurb** [comment]
OK, I'll add in those plugins and their configuration.

**Comment by vidurb** [comment]
PRs have been issued for all plugins, so I'm closing this issue.
